### ISSUE TITLE
MissingPluginException when using in Foreground Service

### ISSUE THREAD

**Issue by saad0510** [hezbr/easy_sms_receiver#2]
I was integrating [`easy_sms_receiver`](https://pub.dev/packages/easy_sms_receiver) in a foreground service using [`flutter_foreground_task`](https://pub.dev/packages/flutter_foreground_task) as shown in the code below.

```dart
import 'package:easy_sms_receiver/easy_sms_receiver.dart';
import 'package:flutter_foreground_task/flutter_foreground_task.dart';

class ForegroundSmsTask extends TaskHandler {
  @override
  void onStart(DateTime timestamp) {
    EasySmsReceiver.instance.stopListenIncomingSms();
    EasySmsReceiver.instance.listenIncomingSms(onNewMessage: (msg) {});
  }

  @override
  void onRepeatEvent(DateTime timestamp) {
    EasySmsReceiver.instance.stopListenIncomingSms();
    EasySmsReceiver.instance.listenIncomingSms(onNewMessage: (msg) {});
  }

  @override
  void onDestroy(DateTime timestamp) {
    EasySmsReceiver.instance.stopListenIncomingSms();
  }
}
```

The messages are getting listened in the `onStart` function, probably because it runs when the app is opened. However, when the app is closed and the `onRepeatEvent` function is executed every few seconds periodically, then it throws the following error:

```
E/flutter (12997): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method stop-receiver on channel easy_sms_receiver)
E/flutter (12997): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332:7)
E/flutter (12997): <asynchronous suspension>
E/flutter (12997): 
E/flutter (12997): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method start-receiver on channel easy_sms_receiver)
E/flutter (12997): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332:7)
E/flutter (12997): <asynchronous suspension>
E/flutter (12997): 
```

**Comment by saad0510** [comment]
The same issue is also observed when using with [`flutter_background_service`](https://pub.dev/packages/flutter_background_service).
